---
- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - php-fpm
    - php-mysql
    - php-curl

- name: Configure php max children
  ini_file:
    path: /etc/php/8.1/fpm/pool.d/www.conf
    section: www
    option: pm.max_children
    value: 20
    backup: yes

- name: Configure php max file size
  ini_file:
    path:  /etc/php/8.1/fpm/php.ini
    section: PHP
    option: upload_max_filesize
    value: 100M
    backup: yes

- name: Configure php max post size
  ini_file:
    path:  /etc/php/8.1/fpm/php.ini
    section: PHP
    option: post_max_size
    value: 100M
    backup: yes


- name: Configure php max input time
  ini_file:
    path:  /etc/php/8.1/fpm/php.ini
    section: PHP
    option: max_input_time
    value: 300
    backup: yes

- name: Restart PHP FPM
  service:
    name: php8.1-fpm
    state: restarted