---

public_facing_hostname: generic-qa.dataportaali.com
internal_hostname: sixodp-{{ deployment_environment_id }}
cms_site_url: localhost
ckan_internal_host: 127.0.0.1:8080
ckan_internal_url: "{{ 'http://' + ckan_internal_host }}"
ckan_site_name: Dataportaali
ckan_featured_orgs:
automatic_updates: true
automatic_updates_recipient: dataportaali-dev@gofore.com joonas.dukpa@tampere.fi

postgres:
  server:
    installed_locally: false
    host: sixodp-{{ deployment_environment_id }}-ckan.{{ rds_domain_common_part }}
    admin_user: ckan_admin
    admin_password: "{{ secret.database_ckan_root_password }}"
    trusted_ip_range: 127.0.0.1/32
  users:
    ckan:
      username: ckan_default
      password: "{{ secret.database_ckan_password }}"
    ckan_datastore: 
      username: datastore_default
      password: "{{ secret.database_ckan_datastore_password }}"
  databases: 
    ckan:
      name: ckan_default
      owner: ckan_default
    ckan_datastore:
      name: datastore_default
      owner: ckan_default

mysql:
  server:
    installed_locally: false
    host: sixodp-{{ deployment_environment_id }}-wordpress.{{ rds_domain_common_part }}
    admin_user: ckan_admin
    admin_password: "{{ secret.database_wordpress_root_password }}"
    trusted_ip_range: 127.0.0.1/32
  users:
    wordpress:
      username: wordpress
      password: "{{ secret.database_wordpress_password }}"
  databases:
    wordpress:
      name: wordpress
      owner: wordpress


nginx:
  use_ssl_certificate: true
  use_selfsigned_certificate: false
  fqdn_common_part: dataportaali.com

acmetool_hostnames:
  - "{{ public_facing_hostname }}"
  - demo.dataportaali.com
  - "phppgadmin.{{ public_facing_hostname }}"

certbot_admin_email: dataportaali-dev@gofore.com
certbot_create_if_missing: true
certbot_certs:
  - domains:
    - "{{ public_facing_hostname }}"
    - demo.dataportaali.com
    - "phppgadmin.{{ public_facing_hostname }}"

solr:
  host: 127.0.0.1
  port: 8983
  listen_address: 127.0.0.1

redis:
  host: 127.0.0.1
  port: 6379

ckan_users:
  admin:
    username: admin
    password: "{{ secret.ckan_admin_password }}"
    email: dataportaali-dev@gofore.com
  harvest:
    username: harvest
    password: "{{ secret.ckan_harvest_password }}"
    email: harvest@localhost
  test:
    username: test
    password: "{{ secret.ckan_test_password }}"
    email: testuser@localhost

wordpress_users:
  admin:
    username: admin
    password: "{{ secret.wordpress_admin_password }}"
    email: dataportaali-dev@gofore.com

ckan_admins:
  - "{{ ckan_users.admin.username }}"
  - "{{ ckan_users.harvest.username }}"

ckan_extensions:
  - ckanext-sixodp
  - ckanext-sixodp_showcase
  - ckanext-scheming
  - ckanext-showcase
  - ckanext-fluent
  #- ckanext-harvest
  - ckanext-cloudstorage
  - ckanext-report
  - ckanext-ga-report
  - ckanext-archiver
  - ckanext-qa
  - ckanext-hierarchy
  - ckanext-disqus
  - ckanext-reminder
  - ckanext-rating
  - ckanext-editor
  - ckanext-collection
  - ckanext-datasetcopy
  #- ckanext-spatial
  - ckanext-datasubmitter
  - ckanext-statistics
  #- ckanext-sixodp_harvester
  - ckanext-sixodp_showcasesubmit
  - ckanext-matomo
  - ckanext-geoview
  - ckanext-sentry

# List of enabled CKAN extensions in load order. Order matters, when templates call super()
enabled_ckan_extensions:
    - datapusher
    - text_view
    - image_view
    - recline_view
    - recline_graph_view
    - recline_grid_view
    - recline_map_view
    - sixodp_showcase
    - matomo
    - qa
    - archiver
    - collection
    - reminder
    - datasetcopy
    - sixodp
    - disqus
    - datastore
    - scheming_datasets
    - scheming_groups
    - fluent
    - report
    - publisher_activity_report
    #- rating
    - hierarchy_display
    - hierarchy_form
    - editor
    #- spatial_metadata
    #- spatial_query
    - datasubmitter
    #- harvest
    - statistics
    #- csw_harvester
    #- sixodp_harvester
    - sixodp_showcasesubmit
    - resource_proxy
    - geo_view
    - sentry


enabled_ckan_aws_extensions: cloudstorage

ckan_site_id: "default"

email_domain: "{{ public_facing_hostname }}"
email:
  smtp_server: localhost
  from: no-reply@{{ email_domain }}
  error_recipient: admin@localhost
  error_from: error@{{ email_domain }}
  contact: not-implemented@localhost

robots_allowed: false

debug_enabled: false

AWS:
  enabled: true
  use_iam_role: true
  ckan_s3_bucket: sixodp-{{ deployment_environment_id }}-datasets
  region: S3_EU_WEST

recaptcha_sitekey: 6LfS9h8UAAAAACsWMtKTxlv81DWXiOAyF82xi1wZ

google_analytics:
  id: UA-98421659-1
  account: Sixodp

matomo:
  domain: '//webanalytics.digiaiiris.com/js/'
  api_domain: 'https://{{ secret.matomo_username }}:{{ secret.matomo_password }}@webanalytics.digiaiiris.com/webanalytics-api/'
  site_id: 1189
  tracker_filename: "tracker.php"
  script_filename: "piwik.min.js"
  token_auth: "{{ secret.matomo_token_auth }}"
  start_date: 10/2023
  show_download_graph: true

disqus_public_key: "{{ secret.disqus_public_key }}"
disqus_secret_key: "{{ secret.disqus_secret_key }}"
disqus_short_name: "{{ secret.disqus_short_name }}"

cookiehub_domain_code: "8f1ccda0"

sentry:
  dsn: "https://b4577d4a1a6f452dbb60df5b74f0db3e@o4504133597855744.ingest.sentry.io/4504133599756288"