---
wordpress_local_plugins:
  - wp-trello
  - wp-api-menus
  - contact-widgets
wordpress_plugins:
  - advanced-custom-fields
  - custom-twitter-feeds
  - polylang
  - google-analytics-dashboard-for-wp
  #- wpcustom-category-image
  - disqus-comment-system
  - wp-recaptcha-integration
  - wordpress-importer
  - wp-user-avatar
  - classic-editor
  - wordpress-seo

removed_wordpress_plugins:
  - addthis

polylang_languages: 
  - { name: 'Suomi', code: 'fi', locale: 'fi', flag: 'fi' }
  - { name: 'Svenska', code: 'sv', locale: 'sv', flag: 'se' }
  - { name: 'English', code: 'en_gb', locale: 'en_GB', flag: 'gb' }

polylang_config: 
  - { option: 'force_lang', value: 1 }
  - { option: 'rewrite', value: 1 }
  - { option: 'hide_default', value: 0 }
  - { option: 'redirect_lang', value: 1 }

# Polylang cli requires ^1.5.0
wp_cli_version: "1.5.1"
wp_cli_checksum: sha512:8dd68c98c6fa00e1acc5e036f9393c8b052937045b5232e4aa0eb4f15773908eae48760607bc853a4f951bd5ba69e5050337e5d9dcfa48df87a12cebb1de3432

wordpress_version: "latest"
