---
#wordpress_local_plugins:
  #- wp-trello
  #- wp-api-menus
  #- contact-widgets
wordpress_plugins:
  - advanced-custom-fields
  #- custom-twitter-feeds
  - polylang
  #- wpcustom-category-image
  - wp-recaptcha-integration
  #- wordpress-importer
  - wp-user-avatars
  - classic-editor
  - wordpress-seo
  - wordfence
  - wp-mail-smtp

removed_wordpress_plugins:
  - addthis
  - wp-user-avatar
  - google-analytics-dashboard-for-wp
  - wp-piwik
  - cookiehub
  - configure-smtp
  - wp-trello
  - disqus-comment-system
  - wp-api-menus
  - custom-twitter-feeds
  - wordpress-importer
  - contact-widgets

polylang_languages: 
  - { name: 'Suomi', code: 'fi', locale: 'fi', flag: 'fi' }
  - { name: 'Svenska', code: 'sv', locale: 'sv', flag: 'se' }
  - { name: 'English', code: 'en_gb', locale: 'en_GB', flag: 'gb' }

polylang_config: 
  - { option: 'force_lang', value: 1 }
  - { option: 'rewrite', value: 1 }
  - { option: 'hide_default', value: 0 }
  - { option: 'redirect_lang', value: 1 }

# Polylang cli requires ^1.5.0
wp_cli_version: "2.11.0"
wp_cli_checksum: sha512:adb12146bab8d829621efed41124dcd0012f9027f47e0228be7080296167566070e4a026a09c3989907840b21de94b7a35f3bfbd5f827c12f27c5803546d1bba

wordpress_version: "latest"
