---

# Warning! This file is open source and available in the Internet! Do not add
# any real secrets here! These are for local Vagrant and for reference.

secret:
  database_ckan_root_password: notinuse
  database_ckan_password: ckan
  database_ckan_datastore_password: ckan
  ckan_admin_password: adminadmin
  ckan_test_password: testtest
  ckan_harvest_password: harvest
  ckan_config:
    beaker_session_secret: A!Ad2#0l$Wcnkm2H^Ehb@ewNaf049jh
    app_instance_uuid: "{ba4abf1a-b1f1-487f-8dd8-7fac52b5aeac}"
  database_wordpress_root_password: notinuse
  database_wordpress_password: wordpress
  wordpress_admin_password: admin
  recaptcha_secret: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
