---

- name: Install dependencies
  apt: name="{{ item }}"
  with_items:
    - gcc
    - libpq-dev
    - libxslt1-dev
    - python-dev
    - zlib1g-dev

- name: Download CKAN
  git:
    repo: https://github.com/ckan/ckan.git
    dest: "{{ cache_path }}/ckan.git"
    bare: yes

- name: Copy recommended setuptools requirements file
  copy: src=requirement-setuptools.txt dest="{{ cache_path }}/requirement-setuptools.txt" mode="0644" owner=root group=root

- name: Install ckan required setuptools
  pip:
    requirements: "{{ cache_path }}/requirement-setuptools.txt"
    virtualenv: "{{ virtualenv }}"

- name: Install CKAN
  pip:
    name: "git+file://{{ cache_path }}/ckan.git@ckan-{{ ckan_version }}#egg=ckan"
    virtualenv: "{{ virtualenv }}"
    extra_args: "--exists-action=s --no-use-pep517"
    editable: yes

- name: Install CKAN requirements
  pip: requirements={{ virtualenv }}/src/ckan/requirements.txt virtualenv={{ virtualenv }}

- name: Install CKAN development/testing requirements
  pip: requirements={{ virtualenv }}/src/ckan/dev-requirements.txt virtualenv={{ virtualenv }}
  when: deployment_environment_id == "build"

- name: Create CKAN paths
  file: path={{ item }} state=directory mode="0770" owner={{ www_user }} group={{ www_group }}
  with_items:
    - "{{ ckan_storage_path }}"
    - /etc/ckan/default
    - "{{ resource_cache_path }}"


- name: Install required pip package
  pip:
    name: uwsgi
    virtualenv: "{{ virtualenv }}"

- name: Copy ckan-uwsgi.ini
  copy:
    src: ckan-uwsgi.ini
    dest: /etc/ckan/default/ckan-uwsgi.ini
    owner: root
    group: root
    mode: "0644"

- name: Ensure path ownerships
  command: chown -R "{{ www_user }}:{{ www_group }}" "{{ ckan_storage_path }}" /etc/ckan/default

- name: Ensure upload path permissions
  command: chmod -R "0770" "{{ ckan_storage_path }}"

- name: Install CKAN core unit test requirements
  pip: requirements={{ virtualenv }}/src/ckan/dev-requirements.txt virtualenv={{ virtualenv }}
  when: deployment_environment_id == "vagrant"

